name: foodhero
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-99.1.beta <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  flutter_speed_dial: ^7.0.0
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  fl_heatmap: ^0.4.5
  percent_indicator: ^4.2.3
  textwrap: ^1.2.0
  image_picker: ^0.8.4+2
  provider: ^6.1.2
  interactive_slider: ^0.2.1
  input_quantity: ^1.2.4
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/fonts/
  # fonts:
  # - family: MouseMemoirs
  # fonts:
  # - asset:

