name: foodhero
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-99.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  http: ^1.2.1
  percent_indicator: ^4.2.3
  textwrap: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    # - assets/fonts/
  # fonts:
  # - family: MouseMemoirs
  # fonts:
  # - asset:
