name: foodhero
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-99.1.beta <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  flutter_speed_dial: ^7.0.0
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  fl_heatmap: ^0.4.5
  percent_indicator: ^4.2.3
  textwrap: ^2.0.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  interactive_slider: ^0.4.0
  input_quantity: ^2.4.1
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  decimal: ^3.0.2
  webview_flutter: ^4.8.0
  
  syncfusion_flutter_charts: ^27.1.57
  flutter_markdown: ^0.7.4+1
  firebase_core: ^3.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/fonts/
  # fonts:
  # - family: MouseMemoirs
  # fonts:
  # - asset:

