name: foodhero
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-99.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^0.8.4+2
  intl: ^0.19.0
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  carousel_slider: ^4.0.0
  percent_indicator: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/FoodHeroLogo.png
    - assets/images/Superfoodhero&background.png
    - assets/images/AllFoodsdecoration.png
    - assets/images/BackButton.png
    - assets/images/ImageOption.png
    - assets/images/Photo.png
    - assets/images/TimeMachine.png
  

  
