// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7op65o2pUqBC_JJvw8L1j134otHgXf-I',
    appId: '1:518083394474:web:94b9aefd994f9fc26c89d3',
    messagingSenderId: '518083394474',
    projectId: 'foodhero-2291b',
    authDomain: 'foodhero-2291b.firebaseapp.com',
    storageBucket: 'foodhero-2291b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdvxI-vHet84wcMbfB24vWhq1hmLiuNWY',
    appId: '1:518083394474:android:0ca50b0d607a0f636c89d3',
    messagingSenderId: '518083394474',
    projectId: 'foodhero-2291b',
    storageBucket: 'foodhero-2291b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqDrwdirVG0JazwbccN9_mDvt5FbDdsT0',
    appId: '1:518083394474:ios:6616f47a6200c8426c89d3',
    messagingSenderId: '518083394474',
    projectId: 'foodhero-2291b',
    storageBucket: 'foodhero-2291b.appspot.com',
    iosBundleId: 'com.example.foodhero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqDrwdirVG0JazwbccN9_mDvt5FbDdsT0',
    appId: '1:518083394474:ios:6616f47a6200c8426c89d3',
    messagingSenderId: '518083394474',
    projectId: 'foodhero-2291b',
    storageBucket: 'foodhero-2291b.appspot.com',
    iosBundleId: 'com.example.foodhero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7op65o2pUqBC_JJvw8L1j134otHgXf-I',
    appId: '1:518083394474:web:dd2a1658f874e0606c89d3',
    messagingSenderId: '518083394474',
    projectId: 'foodhero-2291b',
    authDomain: 'foodhero-2291b.firebaseapp.com',
    storageBucket: 'foodhero-2291b.appspot.com',
  );

}